config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'exchanges#dashboard'

  resources :exchanges do
    get 'dashboard', on: :collection
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
# frozen_string_literal: true

class Exchange < ApplicationRecord
  enum api: { exchange_rate: :exchange_rates, fixer: :fixer }

  def self.currencies
    %w[AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR
       JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR]
  end
end

app/models/exchange_rate_api.rb
# frozen_string_literal: true

class ExchangeRateApi
  include HTTParty
  attr_accessor :base, :start_date, :end_date

  base_uri 'http://api.exchangeratesapi.io'

  def initialize(options = {})
    @options = {
      query: {
        base: options[:base],
        start_at: options[:start_date],
        end_at: options[:end_date],
      }
    }
  end

  def latest
    self.class.get('/latest', @options)
  end

  def historical
    self.class.get('/history', @options)
  end
end

app/models/rate.rb
# frozen_string_literal: true

class Rate < ApplicationRecord
  belongs_to :request_option
end

app/models/request_option.rb
# frozen_string_literal: true

class RequestOption < ApplicationRecord
  has_one :rate, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/exchanges_controller.rb
# frozen_string_literal: true

class ExchangesController < ApplicationController
  def dashboard
    @exchange = Exchange.new
    @currencies_options = Exchange.currencies
    @amount = params[:amount] || 1
    @base = params[:base] || 'EUR'
    @target = params[:target] || 'USD'
    @duration = params[:duration] || 1
    rates = fetch_rates
    @historical_rates = rates[:chart_rates]
    @today_rate = @historical_rates.last[:rate]
    @calculated_amount = multiply(@amount, @today_rate)
    @table_rates = rates[:statistic_rates]
  end

  def index
    @exchanges = Exchange.all
  end

  def edit
    @exchange = Exchange.find(params[:id])
  end

  def create
    @exchange = Exchange.new(exchange_params)

    if @exchange.save
      redirect_to dashboard_exchanges_path(exchange_params.merge(params[:exchange].permit(:duration)))
    else
      redirect_to dashboard_exchanges_path
    end
  end

  def update
    @exchange = Exchange.find(params[:id])

    if @exchange.update_attributes(exchange_params)
      redirect_to action: 'index', notice: 'Exchange was successfully updated.'
    else
      format.html { render action: 'edit' }
    end
  end

  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy

    redirect_to exchanges_url
  end

  private

  def exchange_params
    params.require(:exchange).permit(:amount, :rate, :result, :base, :target)
  end

  def fetch_rates
    client = ExchangesClientService.new(type: Exchange.apis[:exchange_rate],
                                        base: @base,
                                        target: @target,
                                        duration: @duration)
    client.call
  end

  def multiply(amount, rate)
    (amount.to_f * rate.to_f).round(3)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/exchanges_helper.rb
# frozen_string_literal: true

module ExchangesHelper
end

app/views/exchanges/dashboard.html.erb
<h2>
  Exchange Rates
</h2>
<%= simple_form_for @exchange, method: :post do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col-sm">
        <%= f.input :amount, label: 'amount', input_html: {class: "form-control", value: @amount}, required: false %>
      </div>
      <div class="col-sm">
        <%= f.input :rate, label: 'rate', input_html: {class: "form-control", value: @today_rate} %>
      </div>
      <div class="col-sm">
        <%= f.input :result, label: 'result', input_html: {class: "form-control", value: @calculated_amount}, required: false %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <%= f.input :base,
                    collection: @currencies_options,
                    label: 'base',
                    selected: @base,
                    required: false,
                    input_html: {class: "form-control"}
        %>
      </div>
      <div class="col-sm">
        <%= f.input :target,
                    collection: @currencies_options,
                    label: 'target',
                    selected: @target,
                    required: false,
                    input_html: {class: "form-control"}
        %>
      </div>
      <div class="col-sm">
        <%= f.input :duration,
                    collection: 1..52,
                    label: 'last weeks number',
                    selected: @duration,
                    required: false,
                    input_html: {class: "form-control"}
        %>
      </div>
    </div>
  </div>
  <%= f.submit 'Save', class: 'btn btn-success' %>
  <%= link_to 'Exchanges List', exchanges_path, class: 'btn btn-primary' %>
<% end %>
<hr>
<h3>Data</h3>
<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Last Week #</th>
    <th scope="col">Year/Week #</th>
    <th scope="col">Rate For a Week</th>
    <th scope="col">Profit/Lost</th>
    <th scope="col">Highest</th>
    <th scope="col">Lowest</th>
  </tr>
  </thead>
  <tbody>
  <% @table_rates.each_with_index do |rate, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= rate[:year] %>/<%= rate[:week_number] %></td>
      <td><%= rate[:avg_rate] %></td>
      <td><%= (@today_rate - rate[:avg_rate]).round(3) %></td>
      <td><%= rate[:highest] %></td>
      <td><%= rate[:lowest] %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<hr>
<h3>Chart</h3>
<canvas id="myChart" width="1100" height="650"></canvas>
<div id="chart_data" data-historical-rates="<%= @historical_rates.to_json %>"></div>

app/views/exchanges/edit.html.erb
<h2>
  Edit Exchange Rate
</h2>
<%= simple_form_for @exchange, method: :put do |f| %>
  <div class="form-group">

    <%= f.input :amount, label: 'amount', input_html: {class: "form-control"}, required: false %>

    <%= f.input :rate, label: 'rate', input_html: {class: "form-control"} %>

    <%= f.input :result, label: 'result', input_html: {class: "form-control"}, required: false %>

    <%= f.input :base,
                collection: @currencies_options,
                label: 'base',
                required: false,
                input_html: {class: "form-control"}
    %>

    <%= f.input :target,
                collection: @currencies_options,
                label: 'target',
                required: false,
                input_html: {class: "form-control"}
    %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-success' %>
  <%= link_to 'Cancel', exchanges_path, class: 'btn btn-primary' %>
<% end %>

app/views/exchanges/index.html.erb
<h1>Listing exchanges</h1>
<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">amount</th>
    <th scope="col">rate</th>
    <th scope="col">result</th>
    <th scope="col">base currency</th>
    <th scope="col">target currency</th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @exchanges.each do |exchange| %>
    <tr>
      <th scope="row"><%= exchange.amount %></th>
      <td><%= exchange.amount %></td>
      <td><%= exchange.rate %></td>
      <td><%= exchange.result %></td>
      <td><%= exchange.base %></td>
      <td><%= exchange.target %></td>
      <td><%= link_to 'Edit', edit_exchange_path(exchange), class: 'btn btn-info'%></td>
      <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Dashboard', root_url, turbolinks: false, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArcaneBet Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>